### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by MJRamon** [Kein/Stalker2#2]
"Vanilla" branch.
Windows 11, VS 2022 Version 17.11.1

Win SDK
dotnet-sdk-6.0.428-win-x64

Running Stalker2.uproject fails the build and suggest build in source.

Trying to build in VS:
![image](https://github.com/user-attachments/assets/08ce6640-86d2-4856-ab2d-18d349182176)

Trying to build using console:
```
dotnet "G:\UE_5.1\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" Development Win64 -Project="G:/UNREAL_ENGINE/STALKER_VANILLA/Stalker2/Stalker2.uproject" -TargetType=Editor -Progress -NoEngineChanges -NoHotReloadFromIDE
```

```
Using 'git status' to determine working set for adaptive non-unity build (G:\UNREAL_ENGINE\STALKER_VANILLA\Stalker2).
@progress push 5%
@progress 'Generating code...' 0%
@progress 'Generating code...' 67%
@progress 'Generating code...' 100%
@progress pop
Building Stalker2Editor...
Using Visual Studio 2022 14.41.34120 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120) and Windows 10.0.26100.0 SDK (C:\Program Files (x86)\Windows Kits\10).
Determining max actions to execute in parallel (6 physical cores, 12 logical cores)
  Executing up to 6 processes, one per physical core
  Requested 1.5 GB free memory per action, 1.4 GB available: limiting max parallel actions to 1
@progress 'Compiling C++ source code...' 0%
Building 9 actions with 1 process...
ERROR: System.ComponentModel.Win32Exception (998): Invalid access to memory location.
          at EpicGames.Core.ManagedProcessGroup.get_TotalProcessorTime() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Core\ManagedProcess.cs:line 165
          at EpicGames.Core.ManagedProcess.get_TotalProcessorTime() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Core\ManagedProcess.cs:line 1207
          at UnrealBuildTool.ParallelExecutor.RunAction(LinkedAction Action, ManagedProcessGroup ProcessGroup, CancellationToken CancellationToken) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Executors\ParallelExecutor.cs:line 301
          at UnrealBuildTool.ParallelExecutor.ExecuteAction(Task`1[] AntecedentTasks, LinkedAction Action, ManagedProcessGroup ProcessGroup, SemaphoreSlim MaxProcessSemaphore, CancellationToken CancellationToken) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Executors\ParallelExecutor.cs:line 268
@progress 'Compiling C++ source code...' 11%
[1/9] Compile Module.Stalker2.10_of_59.cpp cancelled
ERROR: System.ComponentModel.Win32Exception (998): Invalid access to memory location.
          at EpicGames.Core.ManagedProcessGroup.get_TotalProcessorTime() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Core\ManagedProcess.cs:line 165
          at EpicGames.Core.ManagedProcess.get_TotalProcessorTime() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Core\ManagedProcess.cs:line 1207
          at UnrealBuildTool.ParallelExecutor.RunAction(LinkedAction Action, ManagedProcessGroup ProcessGroup, CancellationToken CancellationToken) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Executors\ParallelExecutor.cs:line 301
          at UnrealBuildTool.ParallelExecutor.ExecuteAction(Task`1[] AntecedentTasks, LinkedAction Action, ManagedProcessGroup ProcessGroup, SemaphoreSlim MaxProcessSemaphore, CancellationToken CancellationToken) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Executors\ParallelExecutor.cs:line 268
@progress 'Compiling C++ source code...' 22%
[2/9] Compile Module.Stalker2.31_of_59.cpp cancelled
ERROR: System.ComponentModel.Win32Exception (998): Invalid access to memory location.
          at EpicGames.Core.ManagedProcessGroup.get_TotalProcessorTime() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Core\ManagedProcess.cs:line 165
          at EpicGames.Core.ManagedProcess.get_TotalProcessorTime() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Core\ManagedProcess.cs:line 1207
          at UnrealBuildTool.ParallelExecutor.RunAction(LinkedAction Action, ManagedProcessGroup ProcessGroup, CancellationToken CancellationToken) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Executors\ParallelExecutor.cs:line 301
          at UnrealBuildTool.ParallelExecutor.ExecuteAction(Task`1[] AntecedentTasks, LinkedAction Action, ManagedProcessGroup ProcessGroup, SemaphoreSlim MaxProcessSemaphore, CancellationToken CancellationToken) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Executors\ParallelExecutor.cs:line 268
@progress 'Compiling C++ source code...' 33%
[3/9] Compile Module.CinematicKeyFrameTracks.cpp cancelled
@progress 'Compiling C++ source code...' 44%
[4/9] Link UnrealEditor-CinematicKeyFrameTracks.dll cancelled
@progress 'Compiling C++ source code...' 56%
[5/9] Link UnrealEditor-CinematicKeyFrameTracks.lib cancelled
ERROR: System.ComponentModel.Win32Exception (998): Invalid access to memory location.
          at EpicGames.Core.ManagedProcessGroup.get_TotalProcessorTime() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Core\ManagedProcess.cs:line 165
          at EpicGames.Core.ManagedProcess.get_TotalProcessorTime() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Core\ManagedProcess.cs:line 1207
          at UnrealBuildTool.ParallelExecutor.RunAction(LinkedAction Action, ManagedProcessGroup ProcessGroup, CancellationToken CancellationToken) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Executors\ParallelExecutor.cs:line 301
          at UnrealBuildTool.ParallelExecutor.ExecuteAction(Task`1[] AntecedentTasks, LinkedAction Action, ManagedProcessGroup ProcessGroup, SemaphoreSlim MaxProcessSemaphore, CancellationToken CancellationToken) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Executors\ParallelExecutor.cs:line 268
@progress 'Compiling C++ source code...' 67%
[6/9] Compile Module.Stalker2.58_of_59.cpp cancelled
@progress 'Compiling C++ source code...' 78%
[7/9] Link UnrealEditor-Stalker2.dll cancelled
@progress 'Compiling C++ source code...' 89%
[8/9] Link UnrealEditor-Stalker2.lib cancelled
@progress 'Compiling C++ source code...' 100%
[9/9] WriteMetadata Stalker2Editor.target cancelled
```

**Comment by Kein** [comment]
These errors not related to the project, it is some generic UE build errors.
Try https://discord.com/invite/unrealsource
